### ISSUE TITLE
Define survey questions

### ISSUE THREAD

**Issue by CevG33ko** [HM-DTLab-SoSe21-SoC/SoSe21-SoC-ChallengeRack#7]
Define needed information in order to design backend fields

**Comment by TobiasWeber93** [comment]
defined in figma https://www.figma.com/file/GcKUHXdPgT2wmxzYohZgfx/DTLab-Intake-UI?node-id=0%3A1

**Comment by CevG33ko** [comment]
https://www.figma.com/file/GcKUHXdPgT2wmxzYohZgfx/DTLab-Intake-UI?node-id=147%3A5
